### ISSUE TITLE
Support for callable defaults

### ISSUE THREAD

**Issue by svtkachenko** [kiwicom/konfetti#14]
Usage example:

```
def read_vault_rancher_token():
    """Read token for thief vault stored in a secret rancher file."""
    open("/run/secrets/vault_token") as secret:
        return secret.read().strip()

VAULT_TOKEN = env("VAULT_TOKEN", default=read_vault_rancher_token)
```

Additionally, we can add a convention that this callable will receive an instance of `KiwiConfig` as a first argument

**Comment by Stranger6667** [comment]
Partially done in 0402fe3bd921f45185c88c20aecd8bba9bdd878f. Not sure about passing a config instance - there is none in case if env var is evaluated in `__str__`
